# ----
# Site

title: Песенник НеЦеР СНГ 
url: "http://netzer.family/"
baseurl: "/"
google_analytics_key: UA-163675948-1
logo: /siteicon.png
description: Аккорды НеЦеР 
author:
  name: НеЦеР СНГ 
  email: netzerfsu@gmail.com
  twitter: # twitter username without the @ symbol
social:

# -----
# Build

timezone: Etc/UTC

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_chapters/1-ma-tov.md"
    values:
      permalink: "/"
      layout: "chapters"
      toc: hash
  -
    scope:
      path: "index.html"
    values:
      layout: "chapters"
      toc: "hash"
  -
    scope:
      type: "chapters"
    values:
      layout: "chapter"

collections:
  chapters:
    output: true
  extras:

# ----
# CloudCannon

_options:
  content:
    format: "h3 h4 h5 h6 p"
    bold: true
    italic: true
    removeformat: true
    link: true
    blockquote: true
    numberedlist: true
    bulletedlist: true
    image: true
    underline: true
    table: true

_comments:
  cover_image: Used as the background of the book cover.
  table_of_contents: Shows/hides the tables of contents.
